### ISSUE TITLE
Question about pulse width modulation

### ISSUE THREAD

**Issue by kylepaulsen** [pendragon-andyh/WebAudio-PulseOscillator#1]
This isn't really an issue but I was reading the section on adding pulse width modulation and it blew my mind when I saw that you were connecting the sawtooth oscillator AND the widthGain to the pulse shaper. It's my understanding that wave shapers only take 1 input (according to MDN anyway: https://developer.mozilla.org/en-US/docs/Web/API/WaveShaperNode). So how in the world does this work? I don't really even understand how the gain node is changing the width of the pulses. It seems to work though!

I'm really impressed by the way. Great job!

**Comment by pendragon-andyh** [comment]
Hi Paul

The waveshaper node only has 1 input,  but (like all inputs) you can
connect any number of connections to it.

The sawtooth oscillator emits a signal with values between -1 and 1. The
gain node is configured to emit a constant value that has the value of the
pwm parameter.

If the pwm parameter has a value of 0.5 the the input to the waveshaper
varies between -0.5 and 1.5. The waveshaper is configured to transform any
positive value to +1 and any negative value to -1. Because the input signal
spends 3/4 of its time above zero, the resulting output will be a pulse
wave that spends most of its time at +1 and only 1/4 time at -1.

If the pwm parameter has a value of zero the the resulting output will be a
square wave (equal time above and below zero). I tried to make this clear
in the graph images.

I hope that this helps you.

The technique is not perfect. I think that it probably suffers from a heap
of aliasing. I will revisit it when I get some spare time.

**Comment by kylepaulsen** [comment]
Hey thanks for getting back to me.

I think I understand the strategy pretty well now. What still kinda confuses me is how the code implements that strategy. However I think I might be getting it.

I drew a picture of how I think the nodes are connected (let me know if this is correct):
![nodes](https://cloud.githubusercontent.com/assets/865580/8389150/be43dd84-1c20-11e5-9376-c064d1248aa4.png)

So, what still confuses me the most is that I think you are feeding 2 waves into the pulseShaper (the lines marked with a red ? mark). My only guess is that these signals are being added together before being fed into the pulseShaper. I guess that would make sense. Is that correct? I guess it would be like a Y = sin(X) + 0.5 graph where 0.5 is from the gain node right? Then the pulseShaper would take over and see that only 1/4th of the signal is below zero, thus making a pulse of that size.

Anyway... Sorry if this is obviously explained somewhere. I'm having a hard time finding information on what happens when you feed more than 1 signal into a node.

Thanks again!

**Comment by pendragon-andyh** [comment]
Hi Kyle

Yes, the two signals are added. I think that this is documented in the spec
for the web audio api (from memory it uses the word "summed"). I have read
the spec several times and normally have it open on my laptop and tablet.

What are you trying to build? The juno106.js project uses this pulse wave
technique to implement a working synth. I am currently writing an envelope
shaper that is more analogue-like.

Regards
Andy

**Comment by kylepaulsen** [comment]
Cool thanks for explaining that. I'm not working on anything yet really... Just learning. However I think the audio API is fascinating. Also I like chip-tune a lot which is why I was looking up how pulse waves work in the first place.

Anyway thanks again for your help! Feel free to close this issue if you want.
